---
# IIS Role Metadata

galaxy_info:
  author: UniCredit Migration Team
  description: IIS Web Server configuration role for Windows
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"

  galaxy_tags:
    - iis
    - windows
    - web_server
    - dotnet

dependencies: []
