---
# SQL Server Client Role Metadata

galaxy_info:
  author: UniCredit Migration Team
  description: SQL Server ODBC driver, command-line tools, and connectivity configuration
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "9"
    - name: Rocky
      versions:
        - "9"
    - name: AlmaLinux
      versions:
        - "9"
    - name: Windows
      versions:
        - "2022"

  galaxy_tags:
    - sqlserver
    - mssql
    - database
    - client
    - odbc
    - windows

dependencies: []
