---
# .NET Application Deployment Role Metadata

galaxy_info:
  author: UniCredit Migration Team
  description: .NET application deployment role for IIS
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"

  galaxy_tags:
    - dotnet
    - iis
    - deployment
    - windows

dependencies:
  - role: iis
