---
# Molecule Galaxy Requirements for Ansible Roles Testing

collections:
  - name: ansible.windows
    version: ">=2.2.0"
  - name: community.windows
    version: ">=2.1.0"
  - name: community.general
    version: ">=8.0.0"
  - name: chocolatey.chocolatey
    version: ">=1.5.0"
